/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FlockrSocialProofApi);
  }
}(this, function(expect, FlockrSocialProofApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MessageRaw', function() {
      beforeEach(function() {
        instance = new FlockrSocialProofApi.MessageRaw();
      });

      it('should create an instance of MessageRaw', function() {
        // TODO: update the code to test MessageRaw
        expect(instance).to.be.a(FlockrSocialProofApi.MessageRaw);
      });

      it('should have the property data (base name: "data")', function() {
        // TODO: update the code to test the property data
        expect(instance).to.have.property('data');
        // expect(instance.data).to.be(expectedValueLiteral);
      });

      it('should have the property _long (base name: "long")', function() {
        // TODO: update the code to test the property _long
        expect(instance).to.have.property('_long');
        // expect(instance._long).to.be(expectedValueLiteral);
      });

      it('should have the property _short (base name: "short")', function() {
        // TODO: update the code to test the property _short
        expect(instance).to.have.property('_short');
        // expect(instance._short).to.be(expectedValueLiteral);
      });

    });
  });

}));
