/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FlockrSocialProofApi);
  }
}(this, function(expect, FlockrSocialProofApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Request', function() {
      beforeEach(function() {
        instance = new FlockrSocialProofApi.Request();
      });

      it('should create an instance of Request', function() {
        // TODO: update the code to test Request
        expect(instance).to.be.a(FlockrSocialProofApi.Request);
      });

      it('should have the property visitor (base name: "visitor")', function() {
        // TODO: update the code to test the property visitor
        expect(instance).to.have.property('visitor');
        // expect(instance.visitor).to.be(expectedValueLiteral);
      });

      it('should have the property location (base name: "location")', function() {
        // TODO: update the code to test the property location
        expect(instance).to.have.property('location');
        // expect(instance.location).to.be(expectedValueLiteral);
      });

      it('should have the property locale (base name: "locale")', function() {
        // TODO: update the code to test the property locale
        expect(instance).to.have.property('locale');
        // expect(instance.locale).to.be(expectedValueLiteral);
      });

      it('should have the property device (base name: "device")', function() {
        // TODO: update the code to test the property device
        expect(instance).to.have.property('device');
        // expect(instance.device).to.be(expectedValueLiteral);
      });

    });
  });

}));
