/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FlockrSocialProofApi);
  }
}(this, function(expect, FlockrSocialProofApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SocialProofProductAltId', function() {
      beforeEach(function() {
        instance = new FlockrSocialProofApi.SocialProofProductAltId();
      });

      it('should create an instance of SocialProofProductAltId', function() {
        // TODO: update the code to test SocialProofProductAltId
        expect(instance).to.be.a(FlockrSocialProofApi.SocialProofProductAltId);
      });

      it('should have the property alternativeId (base name: "alternative_id")', function() {
        // TODO: update the code to test the property alternativeId
        expect(instance).to.have.property('alternativeId');
        // expect(instance.alternativeId).to.be(expectedValueLiteral);
      });

      it('should have the property productId (base name: "product_id")', function() {
        // TODO: update the code to test the property productId
        expect(instance).to.have.property('productId');
        // expect(instance.productId).to.be(expectedValueLiteral);
      });

      it('should have the property site (base name: "site")', function() {
        // TODO: update the code to test the property site
        expect(instance).to.have.property('site');
        // expect(instance.site).to.be(expectedValueLiteral);
      });

    });
  });

}));
