/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The EventEventData model module.
 * @module model/EventEventData
 * @version 1.0.0
 */
export default class EventEventData {
  /**
   * Constructs a new <code>EventEventData</code>.
   * @alias module:model/EventEventData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EventEventData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventEventData} obj Optional instance to populate.
   * @return {module:model/EventEventData} The populated <code>EventEventData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EventEventData();
      if (data.hasOwnProperty('label'))
        obj.label = ApiClient.convertToType(data['label'], 'String');
      if (data.hasOwnProperty('altId'))
        obj.altId = ApiClient.convertToType(data['altId'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'Number');
    }
    return obj;
  }
}

/**
 * The id of the product
 * @member {String} label
 */
EventEventData.prototype.label = undefined;

/**
 * An alternative ID for the product
 * @member {String} altId
 */
EventEventData.prototype.altId = undefined;

/**
 * The value for the event, e.g. the number of items added
 * @member {Number} value
 */
EventEventData.prototype.value = undefined;

