/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import EventEventData from './EventEventData';

/**
 * The EventEvent model module.
 * @module model/EventEvent
 * @version 1.0.0
 */
export default class EventEvent {
  /**
   * Constructs a new <code>EventEvent</code>.
   * @alias module:model/EventEvent
   * @class
   * @param category {String} The category of the event
   * @param name {String} The name of the event
   * @param data {module:model/EventEventData} 
   */
  constructor(category, name, data) {
    this.category = category;
    this.name = name;
    this.data = data;
  }

  /**
   * Constructs a <code>EventEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EventEvent} obj Optional instance to populate.
   * @return {module:model/EventEvent} The populated <code>EventEvent</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EventEvent();
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = EventEventData.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * The category of the event
 * @member {String} category
 */
EventEvent.prototype.category = undefined;

/**
 * The name of the event
 * @member {String} name
 */
EventEvent.prototype.name = undefined;

/**
 * @member {module:model/EventEventData} data
 */
EventEvent.prototype.data = undefined;

