/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The FlockrResult model module.
 * @module model/FlockrResult
 * @version 1.0.0
 */
export default class FlockrResult {
  /**
   * Constructs a new <code>FlockrResult</code>.
   * @alias module:model/FlockrResult
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FlockrResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FlockrResult} obj Optional instance to populate.
   * @return {module:model/FlockrResult} The populated <code>FlockrResult</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FlockrResult();
      if (data.hasOwnProperty('success'))
        obj.success = ApiClient.convertToType(data['success'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Boolean} success
 */
FlockrResult.prototype.success = undefined;

