/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import FlockrResult from './FlockrResult';
import SocialProof from './SocialProof';

/**
 * The Flockr model module.
 * @module model/Flockr
 * @version 1.0.0
 */
export default class Flockr {
  /**
   * Constructs a new <code>Flockr</code>.
   * @alias module:model/Flockr
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Flockr</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Flockr} obj Optional instance to populate.
   * @return {module:model/Flockr} The populated <code>Flockr</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Flockr();
      if (data.hasOwnProperty('result'))
        obj.result = FlockrResult.constructFromObject(data['result']);
      if (data.hasOwnProperty('socialProof'))
        obj.socialProof = ApiClient.convertToType(data['socialProof'], [SocialProof]);
      if (data.hasOwnProperty('recommendations'))
        obj.recommendations = ApiClient.convertToType(data['recommendations'], [SocialProof]);
    }
    return obj;
  }
}

/**
 * @member {module:model/FlockrResult} result
 */
Flockr.prototype.result = undefined;

/**
 * @member {Array.<module:model/SocialProof>} socialProof
 */
Flockr.prototype.socialProof = undefined;

/**
 * @member {Array.<module:model/SocialProof>} recommendations
 */
Flockr.prototype.recommendations = undefined;

