/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import Request from './Request';
import RequestDevice from './RequestDevice';
import RequestLocale from './RequestLocale';
import RequestLocation from './RequestLocation';
import RequestVisitor from './RequestVisitor';

/**
 * The List model module.
 * @module model/List
 * @version 1.0.0
 */
export default class List extends Request {
  /**
   * Constructs a new <code>List</code>.
   * @alias module:model/List
   * @class
   * @extends module:model/Request
   * @param category {} The category of the products - should not be an empty string
   * @param products {} An array of product IDs, also accepts an array of altIds, e.g. [{altId:\"abcdefg\"}]
   * @param visitor {} 
   * @param location {} 
   */
  constructor(category, products, visitor, location) {
    super(visitor, location);
    this.category = category;
    this.products = products;
  }

  /**
   * Constructs a <code>List</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/List} obj Optional instance to populate.
   * @return {module:model/List} The populated <code>List</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new List();
      Request.constructFromObject(data, obj);
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('products'))
        obj.products = ApiClient.convertToType(data['products'], ['String']);
      if (data.hasOwnProperty('recommendations'))
        obj.recommendations = ApiClient.convertToType(data['recommendations'], ['String']);
    }
    return obj;
  }
}

/**
 * The category of the products - should not be an empty string
 * @member {String} category
 */
List.prototype.category = undefined;

/**
 * An array of product IDs, also accepts an array of altIds, e.g. [{altId:\"abcdefg\"}]
 * @member {Array.<String>} products
 */
List.prototype.products = undefined;

/**
 * Optional list of product IDs to fetch proof values for (can be requested on a dedicated call instead if required)
 * @member {Array.<String>} recommendations
 */
List.prototype.recommendations = undefined;

