/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The MessageRawLong model module.
 * @module model/MessageRawLong
 * @version 1.0.0
 */
export default class MessageRawLong {
  /**
   * Constructs a new <code>MessageRawLong</code>.
   * @alias module:model/MessageRawLong
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MessageRawLong</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MessageRawLong} obj Optional instance to populate.
   * @return {module:model/MessageRawLong} The populated <code>MessageRawLong</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MessageRawLong();
      if (data.hasOwnProperty('heading'))
        obj.heading = ApiClient.convertToType(data['heading'], 'String');
      if (data.hasOwnProperty('text'))
        obj.text = ApiClient.convertToType(data['text'], 'String');
    }
    return obj;
  }
}

/**
 * The long heading, these values can be managed in template for the message the Flockr portal
 * @member {String} heading
 */
MessageRawLong.prototype.heading = undefined;

/**
 * The long text, these values can be managed in template for the message the Flockr portal
 * @member {String} text
 */
MessageRawLong.prototype.text = undefined;

