/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import MessageRaw from './MessageRaw';

/**
 * The Message model module.
 * @module model/Message
 * @version 1.0.0
 */
export default class Message {
  /**
   * Constructs a new <code>Message</code>.
   * @alias module:model/Message
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Message</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Message} obj Optional instance to populate.
   * @return {module:model/Message} The populated <code>Message</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Message();
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('code'))
        obj.code = ApiClient.convertToType(data['code'], 'String');
      if (data.hasOwnProperty('message'))
        obj.message = ApiClient.convertToType(data['message'], 'String');
      if (data.hasOwnProperty('raw'))
        obj.raw = MessageRaw.constructFromObject(data['raw']);
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'String');
    }
    return obj;
  }
}

/**
 * Allowed values for the <code>category</code> property.
 * @enum {String}
 * @readonly
 */
Message.CategoryEnum = {
  /**
   * value: "BASKET"
   * @const
   */
  BASKET: "BASKET",

  /**
   * value: "LAST_ORDER_ELAPSED_TIME"
   * @const
   */
  LAST_ORDER_ELAPSED_TIME: "LAST_ORDER_ELAPSED_TIME",

  /**
   * value: "AUDIENCE"
   * @const
   */
  AUDIENCE: "AUDIENCE",

  /**
   * value: "QUANTITY_ORDERS"
   * @const
   */
  QUANTITY_ORDERS: "QUANTITY_ORDERS",

  /**
   * value: "RATING"
   * @const
   */
  RATING: "RATING"
};
/**
 * @member {module:model/Message.CategoryEnum} category
 */
Message.prototype.category = undefined;

/**
 * Allowed values for the <code>code</code> property.
 * @enum {String}
 * @readonly
 */
Message.CodeEnum = {
  /**
   * value: "TS"
   * @const
   */
  TS: "TS",

  /**
   * value: "QPH"
   * @const
   */
  QPH: "QPH",

  /**
   * value: "LPMS"
   * @const
   */
  LPMS: "LPMS",

  /**
   * value: "LPSP"
   * @const
   */
  LPSP: "LPSP",

  /**
   * value: "SLVP"
   * @const
   */
  SLVP: "SLVP",

  /**
   * value: "ATB"
   * @const
   */
  ATB: "ATB",

  /**
   * value: "SLVB"
   * @const
   */
  SLVB: "SLVB",

  /**
   * value: "CAP"
   * @const
   */
  CAP: "CAP",

  /**
   * value: "SLVA"
   * @const
   */
  SLVA: "SLVA",

  /**
   * value: "PRV"
   * @const
   */
  PRV: "PRV",

  /**
   * value: "SZ"
   * @const
   */
  SZ: "SZ"
};
/**
 * @member {module:model/Message.CodeEnum} code
 */
Message.prototype.code = undefined;

/**
 * @member {String} message
 */
Message.prototype.message = undefined;

/**
 * @member {module:model/MessageRaw} raw
 */
Message.prototype.raw = undefined;

/**
 * Allowed values for the <code>time</code> property.
 * @enum {String}
 * @readonly
 */
Message.TimeEnum = {
  /**
   * value: "now_view_count"
   * @const
   */
  nowViewCount: "now_view_count",

  /**
   * value: "now_atb_count"
   * @const
   */
  nowAtbCount: "now_atb_count",

  /**
   * value: "now_purchase_count"
   * @const
   */
  nowPurchaseCount: "now_purchase_count",

  /**
   * value: "now_purchase_sample_count"
   * @const
   */
  nowPurchaseSampleCount: "now_purchase_sample_count",

  /**
   * value: "recent_atb_count"
   * @const
   */
  recentAtbCount: "recent_atb_count",

  /**
   * value: "recent_view_count"
   * @const
   */
  recentViewCount: "recent_view_count",

  /**
   * value: "recent_purchase_count"
   * @const
   */
  recentPurchaseCount: "recent_purchase_count",

  /**
   * value: "recent_purchase_sample_count"
   * @const
   */
  recentPurchaseSampleCount: "recent_purchase_sample_count",

  /**
   * value: "hour1_view_count"
   * @const
   */
  hour1ViewCount: "hour1_view_count",

  /**
   * value: "hour1_atb_count"
   * @const
   */
  hour1AtbCount: "hour1_atb_count",

  /**
   * value: "hour1_purchase_count"
   * @const
   */
  hour1PurchaseCount: "hour1_purchase_count",

  /**
   * value: "hour1_purchase_sample_count"
   * @const
   */
  hour1PurchaseSampleCount: "hour1_purchase_sample_count",

  /**
   * value: "hour3_view_count"
   * @const
   */
  hour3ViewCount: "hour3_view_count",

  /**
   * value: "hour3_atb_count"
   * @const
   */
  hour3AtbCount: "hour3_atb_count",

  /**
   * value: "hour3_purchase_count"
   * @const
   */
  hour3PurchaseCount: "hour3_purchase_count",

  /**
   * value: "hour3_purchase_sample_count"
   * @const
   */
  hour3PurchaseSampleCount: "hour3_purchase_sample_count",

  /**
   * value: "hour12_view_count"
   * @const
   */
  hour12ViewCount: "hour12_view_count",

  /**
   * value: "hour12_atb_count"
   * @const
   */
  hour12AtbCount: "hour12_atb_count",

  /**
   * value: "hour12_purchase_count"
   * @const
   */
  hour12PurchaseCount: "hour12_purchase_count",

  /**
   * value: "hour12_purchase_sample_count"
   * @const
   */
  hour12PurchaseSampleCount: "hour12_purchase_sample_count",

  /**
   * value: "hour24_view_count"
   * @const
   */
  hour24ViewCount: "hour24_view_count",

  /**
   * value: "hour24_atb_count"
   * @const
   */
  hour24AtbCount: "hour24_atb_count",

  /**
   * value: "hour24_purchase_count"
   * @const
   */
  hour24PurchaseCount: "hour24_purchase_count",

  /**
   * value: "hour24_purchase_sample_count"
   * @const
   */
  hour24PurchaseSampleCount: "hour24_purchase_sample_count",

  /**
   * value: "hour48_view_count"
   * @const
   */
  hour48ViewCount: "hour48_view_count",

  /**
   * value: "hour48_atb_count"
   * @const
   */
  hour48AtbCount: "hour48_atb_count",

  /**
   * value: "hour48_purchase_count"
   * @const
   */
  hour48PurchaseCount: "hour48_purchase_count",

  /**
   * value: "hour48_purchase_sample_count"
   * @const
   */
  hour48PurchaseSampleCount: "hour48_purchase_sample_count",

  /**
   * value: "hour120_view_count"
   * @const
   */
  hour120ViewCount: "hour120_view_count",

  /**
   * value: "hour120_atb_count"
   * @const
   */
  hour120AtbCount: "hour120_atb_count",

  /**
   * value: "hour120_purchase_count"
   * @const
   */
  hour120PurchaseCount: "hour120_purchase_count",

  /**
   * value: "hour120_purchase_sample_count"
   * @const
   */
  hour120PurchaseSampleCount: "hour120_purchase_sample_count",

  /**
   * value: "hour168_view_count"
   * @const
   */
  hour168ViewCount: "hour168_view_count",

  /**
   * value: "hour168_atb_count"
   * @const
   */
  hour168AtbCount: "hour168_atb_count",

  /**
   * value: "hour168_purchase_count"
   * @const
   */
  hour168PurchaseCount: "hour168_purchase_count",

  /**
   * value: "hour168_purchase_sample_count"
   * @const
   */
  hour168PurchaseSampleCount: "hour168_purchase_sample_count"
};
/**
 * an enum value or an integer representing the number of hours since last visit (for SLVA, SLVB, SLVP)
 * @member {module:model/Message.TimeEnum} time
 */
Message.prototype.time = undefined;

