/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import MessageRawLong from './MessageRawLong';
import MessageRawShort from './MessageRawShort';

/**
 * The MessageRaw model module.
 * @module model/MessageRaw
 * @version 1.0.0
 */
export default class MessageRaw {
  /**
   * Constructs a new <code>MessageRaw</code>.
   * @alias module:model/MessageRaw
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MessageRaw</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MessageRaw} obj Optional instance to populate.
   * @return {module:model/MessageRaw} The populated <code>MessageRaw</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MessageRaw();
      if (data.hasOwnProperty('data'))
        obj.data = ApiClient.convertToType(data['data'], 'Number');
      if (data.hasOwnProperty('long'))
        obj._long = MessageRawLong.constructFromObject(data['long']);
      if (data.hasOwnProperty('short'))
        obj._short = MessageRawShort.constructFromObject(data['short']);
    }
    return obj;
  }
}

/**
 * @member {Number} data
 */
MessageRaw.prototype.data = undefined;

/**
 * @member {module:model/MessageRawLong} _long
 */
MessageRaw.prototype._long = undefined;

/**
 * @member {module:model/MessageRawShort} _short
 */
MessageRaw.prototype._short = undefined;

