/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The OrderOrderItems model module.
 * @module model/OrderOrderItems
 * @version 1.0.0
 */
export default class OrderOrderItems {
  /**
   * Constructs a new <code>OrderOrderItems</code>.
   * @alias module:model/OrderOrderItems
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderOrderItems</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderOrderItems} obj Optional instance to populate.
   * @return {module:model/OrderOrderItems} The populated <code>OrderOrderItems</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderOrderItems();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'String');
      if (data.hasOwnProperty('altId'))
        obj.altId = ApiClient.convertToType(data['altId'], 'String');
    }
    return obj;
  }
}

/**
 * The product id
 * @member {String} id
 */
OrderOrderItems.prototype.id = undefined;

/**
 * The quantity purchased
 * @member {String} quantity
 */
OrderOrderItems.prototype.quantity = undefined;

/**
 * The altId of the product (if the product ID is not available). You should use either id or altId
 * @member {String} altId
 */
OrderOrderItems.prototype.altId = undefined;

