/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import OrderOrderItems from './OrderOrderItems';
import Request from './Request';
import RequestDevice from './RequestDevice';
import RequestLocale from './RequestLocale';
import RequestLocation from './RequestLocation';
import RequestVisitor from './RequestVisitor';

/**
 * The Order model module.
 * @module model/Order
 * @version 1.0.0
 */
export default class Order extends Request {
  /**
   * Constructs a new <code>Order</code>.
   * @alias module:model/Order
   * @class
   * @extends module:model/Request
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>Order</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Order} obj Optional instance to populate.
   * @return {module:model/Order} The populated <code>Order</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Order();
      Request.constructFromObject(data, obj);
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('totalPrice'))
        obj.totalPrice = ApiClient.convertToType(data['totalPrice'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('orderItems'))
        obj.orderItems = ApiClient.convertToType(data['orderItems'], [OrderOrderItems]);
    }
    return obj;
  }
}

/**
 * The id of the order
 * @member {String} id
 */
Order.prototype.id = undefined;

/**
 * The total value of the order including tax and shipping
 * @member {Number} totalPrice
 */
Order.prototype.totalPrice = undefined;

/**
 * The ISO code for the order currency
 * @member {String} currency
 */
Order.prototype.currency = undefined;

/**
 * @member {Array.<module:model/OrderOrderItems>} orderItems
 */
Order.prototype.orderItems = undefined;

