/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The ProductProduct model module.
 * @module model/ProductProduct
 * @version 1.0.0
 */
export default class ProductProduct {
  /**
   * Constructs a new <code>ProductProduct</code>.
   * @alias module:model/ProductProduct
   * @class
   * @param id {String} The unique ID for the product - must be a string
   */
  constructor(id) {
    this.id = id;
  }

  /**
   * Constructs a <code>ProductProduct</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ProductProduct} obj Optional instance to populate.
   * @return {module:model/ProductProduct} The populated <code>ProductProduct</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ProductProduct();
      if (data.hasOwnProperty('altId'))
        obj.altId = ApiClient.convertToType(data['altId'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('displayPriceUnitPlural'))
        obj.displayPriceUnitPlural = ApiClient.convertToType(data['displayPriceUnitPlural'], 'String');
      if (data.hasOwnProperty('image'))
        obj.image = ApiClient.convertToType(data['image'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('recommendations'))
        obj.recommendations = ApiClient.convertToType(data['recommendations'], [OneOfproductProductRecommendationsItems]);
      if (data.hasOwnProperty('sku'))
        obj.sku = ApiClient.convertToType(data['sku'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
    }
    return obj;
  }
}

/**
 * An alternative ID for the product, this is automaticall mapped to the main ID
 * @member {String} altId
 */
ProductProduct.prototype.altId = undefined;

/**
 * The unique ID for the product - must be a string
 * @member {String} id
 */
ProductProduct.prototype.id = undefined;

/**
 * The category of the product
 * @member {String} category
 */
ProductProduct.prototype.category = undefined;

/**
 * A plural name that the product is sold in, e.g. boxes
 * @member {String} displayPriceUnitPlural
 */
ProductProduct.prototype.displayPriceUnitPlural = undefined;

/**
 * A url of the product image, if supplied Flockr will respond with an image URL that can be used to display the social proof message as an image
 * @member {String} image
 */
ProductProduct.prototype.image = undefined;

/**
 * The name of the product
 * @member {String} name
 */
ProductProduct.prototype.name = undefined;

/**
 * Optional list of product IDs to fetch proof values for (can be requested on a dedicated call instead if required)
 * @member {Array.<String>} recommendations
 */
ProductProduct.prototype.recommendations = undefined;

/**
 * An optinal SKU for the product
 * @member {String} sku
 */
ProductProduct.prototype.sku = undefined;

/**
 * The URL of the product
 * @member {String} url
 */
ProductProduct.prototype.url = undefined;

