/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import ProductProduct from './ProductProduct';
import Request from './Request';
import RequestDevice from './RequestDevice';
import RequestLocale from './RequestLocale';
import RequestLocation from './RequestLocation';
import RequestVisitor from './RequestVisitor';

/**
 * The Product model module.
 * @module model/Product
 * @version 1.0.0
 */
export default class Product extends Request {
  /**
   * Constructs a new <code>Product</code>.
   * @alias module:model/Product
   * @class
   * @extends module:model/Request
   * @param product {} 
   * @param visitor {} 
   * @param location {} 
   */
  constructor(product, visitor, location) {
    super(visitor, location);
    this.product = product;
  }

  /**
   * Constructs a <code>Product</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Product} obj Optional instance to populate.
   * @return {module:model/Product} The populated <code>Product</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Product();
      Request.constructFromObject(data, obj);
      if (data.hasOwnProperty('product'))
        obj.product = ProductProduct.constructFromObject(data['product']);
    }
    return obj;
  }
}

/**
 * @member {module:model/ProductProduct} product
 */
Product.prototype.product = undefined;

