/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import RequestDevice from './RequestDevice';
import RequestLocale from './RequestLocale';
import RequestLocation from './RequestLocation';
import RequestVisitor from './RequestVisitor';

/**
 * The Request model module.
 * @module model/Request
 * @version 1.0.0
 */
export default class Request {
  /**
   * Constructs a new <code>Request</code>.
   * @alias module:model/Request
   * @class
   * @param visitor {module:model/RequestVisitor} 
   * @param location {module:model/RequestLocation} 
   */
  constructor(visitor, location) {
    this.visitor = visitor;
    this.location = location;
  }

  /**
   * Constructs a <code>Request</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Request} obj Optional instance to populate.
   * @return {module:model/Request} The populated <code>Request</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Request();
      if (data.hasOwnProperty('visitor'))
        obj.visitor = RequestVisitor.constructFromObject(data['visitor']);
      if (data.hasOwnProperty('location'))
        obj.location = RequestLocation.constructFromObject(data['location']);
      if (data.hasOwnProperty('locale'))
        obj.locale = RequestLocale.constructFromObject(data['locale']);
      if (data.hasOwnProperty('device'))
        obj.device = RequestDevice.constructFromObject(data['device']);
    }
    return obj;
  }
}

/**
 * @member {module:model/RequestVisitor} visitor
 */
Request.prototype.visitor = undefined;

/**
 * @member {module:model/RequestLocation} location
 */
Request.prototype.location = undefined;

/**
 * @member {module:model/RequestLocale} locale
 */
Request.prototype.locale = undefined;

/**
 * @member {module:model/RequestDevice} device
 */
Request.prototype.device = undefined;

