/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RequestLocale model module.
 * @module model/RequestLocale
 * @version 1.0.0
 */
export default class RequestLocale {
  /**
   * Constructs a new <code>RequestLocale</code>.
   * @alias module:model/RequestLocale
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RequestLocale</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestLocale} obj Optional instance to populate.
   * @return {module:model/RequestLocale} The populated <code>RequestLocale</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RequestLocale();
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} language
 */
RequestLocale.prototype.language = undefined;

