/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RequestDeviceScreen model module.
 * @module model/RequestDeviceScreen
 * @version 1.0.0
 */
export default class RequestDeviceScreen {
  /**
   * Constructs a new <code>RequestDeviceScreen</code>.
   * @alias module:model/RequestDeviceScreen
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RequestDeviceScreen</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestDeviceScreen} obj Optional instance to populate.
   * @return {module:model/RequestDeviceScreen} The populated <code>RequestDeviceScreen</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RequestDeviceScreen();
      if (data.hasOwnProperty('height'))
        obj.height = ApiClient.convertToType(data['height'], 'Number');
      if (data.hasOwnProperty('width'))
        obj.width = ApiClient.convertToType(data['width'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} height
 */
RequestDeviceScreen.prototype.height = undefined;

/**
 * @member {Number} width
 */
RequestDeviceScreen.prototype.width = undefined;

