/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import RequestDeviceScreen from './RequestDeviceScreen';

/**
 * The RequestDevice model module.
 * @module model/RequestDevice
 * @version 1.0.0
 */
export default class RequestDevice {
  /**
   * Constructs a new <code>RequestDevice</code>.
   * @alias module:model/RequestDevice
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RequestDevice</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestDevice} obj Optional instance to populate.
   * @return {module:model/RequestDevice} The populated <code>RequestDevice</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RequestDevice();
      if (data.hasOwnProperty('screen'))
        obj.screen = RequestDeviceScreen.constructFromObject(data['screen']);
      if (data.hasOwnProperty('userAgent'))
        obj.userAgent = ApiClient.convertToType(data['userAgent'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/RequestDeviceScreen} screen
 */
RequestDevice.prototype.screen = undefined;

/**
 * @member {String} userAgent
 */
RequestDevice.prototype.userAgent = undefined;

