/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The RequestVisitor model module.
 * @module model/RequestVisitor
 * @version 1.0.0
 */
export default class RequestVisitor {
  /**
   * Constructs a new <code>RequestVisitor</code>.
   * @alias module:model/RequestVisitor
   * @class
   * @param id {String} A unique id for the visitor
   * @param sessionId {String} A unique id for the session
   */
  constructor(id, sessionId) {
    this.id = id;
    this.sessionId = sessionId;
  }

  /**
   * Constructs a <code>RequestVisitor</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RequestVisitor} obj Optional instance to populate.
   * @return {module:model/RequestVisitor} The populated <code>RequestVisitor</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RequestVisitor();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('sessionId'))
        obj.sessionId = ApiClient.convertToType(data['sessionId'], 'String');
    }
    return obj;
  }
}

/**
 * A unique id for the visitor
 * @member {String} id
 */
RequestVisitor.prototype.id = undefined;

/**
 * A unique id for the session
 * @member {String} sessionId
 */
RequestVisitor.prototype.sessionId = undefined;

