/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';
import SocialProofProductAltId from './SocialProofProductAltId';

/**
 * The SocialProofProduct model module.
 * @module model/SocialProofProduct
 * @version 1.0.0
 */
export default class SocialProofProduct {
  /**
   * Constructs a new <code>SocialProofProduct</code>.
   * @alias module:model/SocialProofProduct
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SocialProofProduct</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SocialProofProduct} obj Optional instance to populate.
   * @return {module:model/SocialProofProduct} The populated <code>SocialProofProduct</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SocialProofProduct();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('altId'))
        obj.altId = SocialProofProductAltId.constructFromObject(data['altId']);
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
SocialProofProduct.prototype.id = undefined;

/**
 * @member {module:model/SocialProofProductAltId} altId
 */
SocialProofProduct.prototype.altId = undefined;

