/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.58
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from '../ApiClient';

/**
 * The SocialProofProductAltId model module.
 * @module model/SocialProofProductAltId
 * @version 1.0.0
 */
export default class SocialProofProductAltId {
  /**
   * Constructs a new <code>SocialProofProductAltId</code>.
   * @alias module:model/SocialProofProductAltId
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SocialProofProductAltId</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SocialProofProductAltId} obj Optional instance to populate.
   * @return {module:model/SocialProofProductAltId} The populated <code>SocialProofProductAltId</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SocialProofProductAltId();
      if (data.hasOwnProperty('alternative_id'))
        obj.alternativeId = ApiClient.convertToType(data['alternative_id'], 'String');
      if (data.hasOwnProperty('product_id'))
        obj.productId = ApiClient.convertToType(data['product_id'], 'String');
      if (data.hasOwnProperty('site'))
        obj.site = ApiClient.convertToType(data['site'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} alternativeId
 */
SocialProofProductAltId.prototype.alternativeId = undefined;

/**
 * @member {String} productId
 */
SocialProofProductAltId.prototype.productId = undefined;

/**
 * @member {String} site
 */
SocialProofProductAltId.prototype.site = undefined;

