/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.62
 *
 * Do not edit the class manually.
 *
 */
import ApiClient from './ApiClient';
import AltId from './model/AltId';
import Event from './model/Event';
import EventEvent from './model/EventEvent';
import EventEventData from './model/EventEventData';
import Flockr from './model/Flockr';
import FlockrResult from './model/FlockrResult';
import List from './model/List';
import ListOnly from './model/ListOnly';
import Message from './model/Message';
import MessageRaw from './model/MessageRaw';
import MessageRawLong from './model/MessageRawLong';
import MessageRawShort from './model/MessageRawShort';
import OneOfproductProductRecommendationsItems from './model/OneOfproductProductRecommendationsItems';
import Order from './model/Order';
import OrderOrderItems from './model/OrderOrderItems';
import Product from './model/Product';
import ProductProduct from './model/ProductProduct';
import Request from './model/Request';
import RequestDevice from './model/RequestDevice';
import RequestDeviceScreen from './model/RequestDeviceScreen';
import RequestLocale from './model/RequestLocale';
import RequestLocation from './model/RequestLocation';
import RequestVisitor from './model/RequestVisitor';
import SocialProof from './model/SocialProof';
import SocialProofProduct from './model/SocialProofProduct';
import SocialProofProductAltId from './model/SocialProofProductAltId';
import CartApi from './api/CartApi';
import ConversionOrderApi from './api/ConversionOrderApi';
import CustomerEventApi from './api/CustomerEventApi';
import ImageApi from './api/ImageApi';
import ListApi from './api/ListApi';
import PredictiveSearchApi from './api/PredictiveSearchApi';
import ProductDetailsApi from './api/ProductDetailsApi';
import ProductListApi from './api/ProductListApi';
import ProductRecommendationsApi from './api/ProductRecommendationsApi';
import SamplesApi from './api/SamplesApi';

/**
* API_for_sending_product_user_actions_and_retrieving_social_proof.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var FlockrSocialProofApi = require('index'); // See note below*.
* var xxxSvc = new FlockrSocialProofApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new FlockrSocialProofApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new FlockrSocialProofApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new FlockrSocialProofApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AltId model constructor.
     * @property {module:model/AltId}
     */
    AltId,

    /**
     * The Event model constructor.
     * @property {module:model/Event}
     */
    Event,

    /**
     * The EventEvent model constructor.
     * @property {module:model/EventEvent}
     */
    EventEvent,

    /**
     * The EventEventData model constructor.
     * @property {module:model/EventEventData}
     */
    EventEventData,

    /**
     * The Flockr model constructor.
     * @property {module:model/Flockr}
     */
    Flockr,

    /**
     * The FlockrResult model constructor.
     * @property {module:model/FlockrResult}
     */
    FlockrResult,

    /**
     * The List model constructor.
     * @property {module:model/List}
     */
    List,

    /**
     * The ListOnly model constructor.
     * @property {module:model/ListOnly}
     */
    ListOnly,

    /**
     * The Message model constructor.
     * @property {module:model/Message}
     */
    Message,

    /**
     * The MessageRaw model constructor.
     * @property {module:model/MessageRaw}
     */
    MessageRaw,

    /**
     * The MessageRawLong model constructor.
     * @property {module:model/MessageRawLong}
     */
    MessageRawLong,

    /**
     * The MessageRawShort model constructor.
     * @property {module:model/MessageRawShort}
     */
    MessageRawShort,

    /**
     * The OneOfproductProductRecommendationsItems model constructor.
     * @property {module:model/OneOfproductProductRecommendationsItems}
     */
    OneOfproductProductRecommendationsItems,

    /**
     * The Order model constructor.
     * @property {module:model/Order}
     */
    Order,

    /**
     * The OrderOrderItems model constructor.
     * @property {module:model/OrderOrderItems}
     */
    OrderOrderItems,

    /**
     * The Product model constructor.
     * @property {module:model/Product}
     */
    Product,

    /**
     * The ProductProduct model constructor.
     * @property {module:model/ProductProduct}
     */
    ProductProduct,

    /**
     * The Request model constructor.
     * @property {module:model/Request}
     */
    Request,

    /**
     * The RequestDevice model constructor.
     * @property {module:model/RequestDevice}
     */
    RequestDevice,

    /**
     * The RequestDeviceScreen model constructor.
     * @property {module:model/RequestDeviceScreen}
     */
    RequestDeviceScreen,

    /**
     * The RequestLocale model constructor.
     * @property {module:model/RequestLocale}
     */
    RequestLocale,

    /**
     * The RequestLocation model constructor.
     * @property {module:model/RequestLocation}
     */
    RequestLocation,

    /**
     * The RequestVisitor model constructor.
     * @property {module:model/RequestVisitor}
     */
    RequestVisitor,

    /**
     * The SocialProof model constructor.
     * @property {module:model/SocialProof}
     */
    SocialProof,

    /**
     * The SocialProofProduct model constructor.
     * @property {module:model/SocialProofProduct}
     */
    SocialProofProduct,

    /**
     * The SocialProofProductAltId model constructor.
     * @property {module:model/SocialProofProductAltId}
     */
    SocialProofProductAltId,

    /**
    * The CartApi service constructor.
    * @property {module:api/CartApi}
    */
    CartApi,

    /**
    * The ConversionOrderApi service constructor.
    * @property {module:api/ConversionOrderApi}
    */
    ConversionOrderApi,

    /**
    * The CustomerEventApi service constructor.
    * @property {module:api/CustomerEventApi}
    */
    CustomerEventApi,

    /**
    * The ImageApi service constructor.
    * @property {module:api/ImageApi}
    */
    ImageApi,

    /**
    * The ListApi service constructor.
    * @property {module:api/ListApi}
    */
    ListApi,

    /**
    * The PredictiveSearchApi service constructor.
    * @property {module:api/PredictiveSearchApi}
    */
    PredictiveSearchApi,

    /**
    * The ProductDetailsApi service constructor.
    * @property {module:api/ProductDetailsApi}
    */
    ProductDetailsApi,

    /**
    * The ProductListApi service constructor.
    * @property {module:api/ProductListApi}
    */
    ProductListApi,

    /**
    * The ProductRecommendationsApi service constructor.
    * @property {module:api/ProductRecommendationsApi}
    */
    ProductRecommendationsApi,

    /**
    * The SamplesApi service constructor.
    * @property {module:api/SamplesApi}
    */
    SamplesApi
};
