/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Event;
import io.swagger.client.model.Flockr;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for CustomerEventApi
 */
@Ignore
public class CustomerEventApiTest {

    private final CustomerEventApi api = new CustomerEventApi();

    /**
     * Registers an event for the customer
     *
     * By passing the details of event for a product, the social proof for that product is updated. The social proof for that product is returned 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void eventTest() throws Exception {
        Event body = null;
        String apiKey = null;
        Flockr response = api.event(body, apiKey);

        // TODO: test validations
    }
}
