/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import java.io.File;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ImageApi
 */
@Ignore
public class ImageApiTest {

    private final ImageApi api = new ImageApi();

    /**
     * returns an image containing the social proof for the product, Note use https://flockr-cdn.com as the host in production
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void imageTest() throws Exception {
        String apiKey = null;
        String image = null;
        String productId = null;
        String visitorId = null;
        String sessionId = null;
        String host = null;
        String location = null;
        Boolean transparent = null;
        File response = api.image(apiKey, image, productId, visitorId, sessionId, host, location, transparent);

        // TODO: test validations
    }
}
