/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Flockr;
import io.swagger.client.model.Product;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ProductDetailsApi
 */
@Ignore
public class ProductDetailsApiTest {

    private final ProductDetailsApi api = new ProductDetailsApi();

    /**
     * saves a product visit and returns social proof
     *
     * By passing the details of a product visit, the social proof for that product is updagted, a product visit is counted once per session. The social proof for that product is returned 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void productVisitTest() throws Exception {
        Product body = null;
        String apiKey = null;
        String flockrDemo = null;
        String flockrFakeData = null;
        Boolean transparent = null;
        Flockr response = api.productVisit(body, apiKey, flockrDemo, flockrFakeData, transparent);

        // TODO: test validations
    }
}
