/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.math.BigDecimal;
/**
 * EventEventData
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-10-11T13:43:34.865069393Z[GMT]")

public class EventEventData {
  @SerializedName("label")
  private String label = null;

  @SerializedName("altId")
  private String altId = null;

  @SerializedName("value")
  private BigDecimal value = null;

  public EventEventData label(String label) {
    this.label = label;
    return this;
  }

   /**
   * The id of the product (you can specify label, label &amp; altId or altId)
   * @return label
  **/
  @Schema(example = "1725", description = "The id of the product (you can specify label, label & altId or altId)")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public EventEventData altId(String altId) {
    this.altId = altId;
    return this;
  }

   /**
   * An alternative ID for the product (you can specify label, label &amp; altId or altId)
   * @return altId
  **/
  @Schema(example = "abcdefg", description = "An alternative ID for the product (you can specify label, label & altId or altId)")
  public String getAltId() {
    return altId;
  }

  public void setAltId(String altId) {
    this.altId = altId;
  }

  public EventEventData value(BigDecimal value) {
    this.value = value;
    return this;
  }

   /**
   * The value for the event, e.g. the number of items added
   * @return value
  **/
  @Schema(example = "1", required = true, description = "The value for the event, e.g. the number of items added")
  public BigDecimal getValue() {
    return value;
  }

  public void setValue(BigDecimal value) {
    this.value = value;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventEventData eventEventData = (EventEventData) o;
    return Objects.equals(this.label, eventEventData.label) &&
        Objects.equals(this.altId, eventEventData.altId) &&
        Objects.equals(this.value, eventEventData.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(label, altId, value);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventEventData {\n");
    
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    altId: ").append(toIndentedString(altId)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
