/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * RequestVisitor
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-09T13:49:56.363387768Z[GMT]")

public class RequestVisitor {
  @SerializedName("id")
  private String id = null;

  @SerializedName("sessionId")
  private String sessionId = null;

  public RequestVisitor id(String id) {
    this.id = id;
    return this;
  }

   /**
   * A unique id for the visitor
   * @return id
  **/
  @Schema(example = "51102fbc-525c-41a2-b4e1-1606e19f3f88", description = "A unique id for the visitor")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RequestVisitor sessionId(String sessionId) {
    this.sessionId = sessionId;
    return this;
  }

   /**
   * A unique id for the session
   * @return sessionId
  **/
  @Schema(example = "5e537d75-72ff-47df-a581-d5f0d0316062", description = "A unique id for the session")
  public String getSessionId() {
    return sessionId;
  }

  public void setSessionId(String sessionId) {
    this.sessionId = sessionId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RequestVisitor requestVisitor = (RequestVisitor) o;
    return Objects.equals(this.id, requestVisitor.id) &&
        Objects.equals(this.sessionId, requestVisitor.sessionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, sessionId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RequestVisitor {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    sessionId: ").append(toIndentedString(sessionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
