/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.Message;
import io.swagger.client.model.SocialProofProduct;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * SocialProof
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-10-11T13:43:34.865069393Z[GMT]")

public class SocialProof {
  @SerializedName("messages")
  private List<Message> messages = null;

  @SerializedName("image")
  private String image = null;

  @SerializedName("product")
  private SocialProofProduct product = null;

  public SocialProof messages(List<Message> messages) {
    this.messages = messages;
    return this;
  }

  public SocialProof addMessagesItem(Message messagesItem) {
    if (this.messages == null) {
      this.messages = new ArrayList<Message>();
    }
    this.messages.add(messagesItem);
    return this;
  }

   /**
   * Get messages
   * @return messages
  **/
  @Schema(description = "")
  public List<Message> getMessages() {
    return messages;
  }

  public void setMessages(List<Message> messages) {
    this.messages = messages;
  }

  public SocialProof image(String image) {
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @Schema(example = "https://flockr-cdn.com/api/v2/key/{apiKey}/image?host=app&image=https%3A%2F%2Fwww.toppstiles.co.uk%2Fstatic%2Fmedia%2Fcatalog%2Fproduct%2Fc%2Fa%2F634119_metro-white-tile_7.jpg&productId=1725&visitorId=51102fbc-525c-41a2-b4e1-1606e19f3f88&sessionId=5e537d75-72ff-47df-a581-d5f0d0316062&transparent=false", description = "")
  public String getImage() {
    return image;
  }

  public void setImage(String image) {
    this.image = image;
  }

  public SocialProof product(SocialProofProduct product) {
    this.product = product;
    return this;
  }

   /**
   * Get product
   * @return product
  **/
  @Schema(description = "")
  public SocialProofProduct getProduct() {
    return product;
  }

  public void setProduct(SocialProofProduct product) {
    this.product = product;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SocialProof socialProof = (SocialProof) o;
    return Objects.equals(this.messages, socialProof.messages) &&
        Objects.equals(this.image, socialProof.image) &&
        Objects.equals(this.product, socialProof.product);
  }

  @Override
  public int hashCode() {
    return Objects.hash(messages, image, product);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SocialProof {\n");
    
    sb.append("    messages: ").append(toIndentedString(messages)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
