/*
 * Flockr Social Proof API
 * API for sending product user actions and retrieving social proof
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@flockr.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * SocialProofProductAltId
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-08-09T14:32:01.000659766Z[GMT]")

public class SocialProofProductAltId {
  @SerializedName("alternative_id")
  private String alternativeId = null;

  @SerializedName("product_id")
  private String productId = null;

  @SerializedName("site")
  private String site = null;

  public SocialProofProductAltId alternativeId(String alternativeId) {
    this.alternativeId = alternativeId;
    return this;
  }

   /**
   * Get alternativeId
   * @return alternativeId
  **/
  @Schema(example = "abcdefg", description = "")
  public String getAlternativeId() {
    return alternativeId;
  }

  public void setAlternativeId(String alternativeId) {
    this.alternativeId = alternativeId;
  }

  public SocialProofProductAltId productId(String productId) {
    this.productId = productId;
    return this;
  }

   /**
   * Get productId
   * @return productId
  **/
  @Schema(example = "7515", description = "")
  public String getProductId() {
    return productId;
  }

  public void setProductId(String productId) {
    this.productId = productId;
  }

  public SocialProofProductAltId site(String site) {
    this.site = site;
    return this;
  }

   /**
   * Get site
   * @return site
  **/
  @Schema(example = "www.toppstiles.co.uk", description = "")
  public String getSite() {
    return site;
  }

  public void setSite(String site) {
    this.site = site;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SocialProofProductAltId socialProofProductAltId = (SocialProofProductAltId) o;
    return Objects.equals(this.alternativeId, socialProofProductAltId.alternativeId) &&
        Objects.equals(this.productId, socialProofProductAltId.productId) &&
        Objects.equals(this.site, socialProofProductAltId.site);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alternativeId, productId, site);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SocialProofProductAltId {\n");
    
    sb.append("    alternativeId: ").append(toIndentedString(alternativeId)).append("\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    site: ").append(toIndentedString(site)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
